### ISSUE TITLE
Introduce Math mode

### ISSUE THREAD

**Issue by leipert** [nylki/pen-paper-coffee-syntax#10]
I use `$...$` and `$$...$$` styles on a regular basis. Is there any way to style them?

Example:
```markdown
I like inline too $ E=mc^2 $

$$
\begin{aligned}
W &= (r,S,R)\\
S  &= K \cup I \neq \emptyset\\
R  &\subseteq E \times S \cup (r, s \in S) \neq \emptyset
\end{aligned}
$$
```

**Comment by nylki** [comment]
The actual recognition of such patterns has to be implemented in the language package. In this case the ![gfm-language/Github flavored markdown package](https://github.com/atom/language-gfm). I am not sure they will implement inline LaTeX syntax highlighting, as it is not supported by github, only pandoc and possibly others.

However, I planned to implement syntax highlighting of *pandoc's* markdown features like inline *LaTeX* math in a separate package ![Pandoc flavored markdown](https://github.com/nylki/language-pfm) which is a fork from the language-gfm package. Unfortunately i haven't had much time to do so.

**Comment by leipert** [comment]
Well thank you, maybe I will have a look at your second repo and help you ;)

**Comment by nylki** [comment]
@leipert I would be delighted. :)

**Comment by nylki** [comment]
@leipert for your information, you may aswell look at https://github.com/retrography/language-gfm by @retrography. He is also doing a language-pfm package. so many choices!

**Comment by retrography** [comment]
@leipert @nylki I actually made a pull request on the original gfm package in order to integrate small modifications that improved Pandoc compatibility and to my great surprise it was accepted. Now you can terminate your metadata block with ... and you can use Pandoc style citations and gfm won't be confused.

**Comment by retrography** [comment]
@nylki Oh, I just noticed your suggestion on language-gfm. After I actually wrote a conference paper with Pandoc and Atom I came to the conclusion that a proper implementation of the Pandoc flavoured markdown will take way too many deviations from the standard github flavoured one. I think we should launch a proper package of we are serious about this. I didn't find it particularly difficult to implement the two mods above. The Travis Continuous Integration that is enabled on the gfm package really helps to understand whether your mods will break the package or not. The trouble is that I don't know how to set that up and how to implement the proper test files.

**Comment by leipert** [comment]
I know how to setup travis or wercker CI and I am eager to fully support a pandoc flavored markdown. Where do we want to start and move the discussion? Should I create PRs to https://github.com/nylki/language-pfm or https://github.com/retrography/language-gfm ?

**Comment by retrography** [comment]
@leipert My modifications are modest and have already been integrated into the main GFM branch. I would start either with @nylki or the main GFM branch and would try to integrate all the mods from the other branch. 

I see at least three important issues on the way to maintaining a full PFM language pack: 

1) ATOM language packs determine patterns using Regexp. It is important to keep these neat and tidy. If you make a pull request on the original GFM pack you will see how fussy ATOM people are about this. They want to make sure your Regexps are not too inclusive or too exclusive and that they are not greedy to the point that they slow down the editor. Someone should take care of these as people submit patches.

2) Pandoc is a very flexible tool and it comes with way too many options. Options are supported in ATOM through config files and preferences pages, but implementing them takes time and deliberate effort. One should put some order and logic into these options. Let's say tables: Do you want simple tables, multiline tables, pipe tables or grid tables? With caption or without captions? And are these incompatible and need to be enabled/disabled through preferences. If I know someone is ready to go through these logical intricacies and keep the house in order, I am more than willing to submit my patches and add the features that I get to use little by little and while I get to use them while writing papers.

3) Pandoc supports many 3rd party languages. For example, take Mathjax or TeX. Highlighting those languages takes an extra integration effort. Maybe ATOM has a feature for nested language highlighting?

By the way, one obvious initial task is to check and try to translate what the Pandoc language packs for the other editors have already implemented. For example, VIM has one. Can we take anything from there?

**Comment by nylki** [comment]
My changes only include renaming everything relevant from *gfm* to *pfm* and a not working attempt to highlight the math-dollars (which highlights too much).

So feel free to fork it, or better start from a fresh fork of *gfm*, as quite a few addition were added in the meantime to *gfm* i suppose. I agree with the points  stated by @retrography. Especially **point 2** can be tricky to get right, considering all the possible [extensions](http://johnmacfarlane.net/pandoc/README.html#pandocs-markdown) of pandoc.

Regarding **point 3**: I think atom does support nested language highlighting, compare for example a *html* document with *javascript* in `<script>` tags. The *html* is highlighted properly, as is the *javascript*. The embedded *javascript* gets following scope: `source.js.embedded.html`

 a look at that package might be worth it, when implementing inline *LaTeX* in *markdown*.

**Comment by leipert** [comment]
@nylki @retrography The package is in the wild [language-pfm](https://atom.io/packages/language-pfm)

Math, Definition Lists and Inline HTML work.

See the pull request: #11

**Comment by retrography** [comment]
@leipert Great! Will use it soon.
