### ISSUE TITLE
Support for underlined headings

### ISSUE THREAD

**Issue by flesser** [nylki/pen-paper-coffee-syntax#13]
Currently, only headings preceeded with # are highlighted.
The alternate underline-ish style for H1 and H2 does not seem to be supported yet:

![screenshot](https://cloud.githubusercontent.com/assets/510681/6780861/05b3c2b8-d169-11e4-9201-0509c4056bdd.png)

**Comment by nylki** [comment]
Hi Florian,
The recognition of language features, such as alternative headings is not the task of the syntax theme (pen-paper-coffee in this case), but of the grammar/language package. Please open an issue either at [github flavored markdown](https://github.com/atom/language-gfm) or at [pandoc flavored markdown](https://github.com/leipert/language-pfm)
