### ISSUE TITLE
JSDoc/YUIDoc styling

### ISSUE THREAD

**Issue by balupton** [nylki/pen-paper-coffee-syntax#14]
Not sure if this is an issue with Atom, or the theme:

https://discuss.atom.io/t/jsdoc-yuidoc-syntax-highlighting/15934

**Comment by nylki** [comment]
It is not an issue of the theme. However if the [javascript language package](https://github.com/atom/language-javascript) will support JsDoc, I'll be happy to take a look what styling might would make most sense.

Next time you can check wether some language features are recognized by the language package but maybe not the syntax package, you can `ctrl` `alt` `shift` `p` to log the scope at the current cursor position and see if it is any different to eg. a standard comment. You can also open the developer tools ( *View -> Developer -> open tools*) to take a look at the DOM.

**Comment by balupton** [comment]
@nylki cool thanks for the tip! Cross-posted here: https://github.com/atom/language-javascript/issues/130

Thanks for the awesome theme! Use it everyday for everything.

**Comment by nylki** [comment]
@balupton Glad you like it and find it useful!
I am personally using it as well both for writing and coding, so it's good to hear it the styling makes sense for other people too.
