### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by ksilin** [nylki/pen-paper-coffee-syntax#15]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `pen-paper-coffee-syntax` package
```
ThemePackage.getStylesheetsPath (/opt/atom/resources/app/src/package.js:433:9)
<unknown> (/opt/atom/resources/app/src/theme-manager.js:434:35)
```

**Comment by nylki** [comment]
It's fixed on github, gotta push a new release via apm.

**Comment by ksilin** [comment]
Cool, thanks :+1:
