### ISSUE TITLE
Strange positioning of h1 in new document

### ISSUE THREAD

**Issue by markoa** [nylki/pen-paper-coffee-syntax#2]
Hi, I really like your theme. Here's a strange thing I found:

- Open Atom.
- New file.
- Write a header.

![screen shot 2014-10-14 at 08 01 53](https://cloud.githubusercontent.com/assets/8651/4624610/a2f8de58-5367-11e4-9701-4ddbf76df0b5.png)

**Comment by nylki** [comment]
I am reopening it, still not fixed (just checked on OS X).
Help would be appreciated.

**Comment by braver** [comment]
@nylki I may have a fix for that. It puts a bit of padding on the scroll-view (i.e. the editing area) and gutter. I haven't found a situation where that causes a problem, but could do with some more testing perhaps.

**Comment by nylki** [comment]
@braver Thx for the commits! I will close this issue when I a have tested your changes with different fonts, font sizes and different setups for a while.

**Comment by nylki** [comment]
current solution is to create 0.5em space on top, so it is dynamicly margined, no matter what the font size etc. is, see commit: 0598b6f828885e6f4b9a3dd5d65d153caa4ee56d
