### ISSUE TITLE
Autocomplete pop-ups hide text

### ISSUE THREAD

**Issue by sbaack** [nylki/pen-paper-coffee-syntax#22]
The pop-ups from autocomplete plus are a bit too high and hide the text I'm writing:

<img width="318" alt="screen shot 2015-10-02 at 2 05 52 pm" src="https://cloud.githubusercontent.com/assets/8274140/10246160/f8d0fe10-690e-11e5-97fa-735b0239055f.png">

Minor thing, but I find it a bit distracting in the writing process.

**Comment by nylki** [comment]
I am innocent, I have nothing to do with autocomplete popup positioning ;)
Please file a bug either at [autocomplete plus](https://github.com/atom/autocomplete-plus/) (or the UI-theme you are using, in case they are changing the positioning of the popup)

**Comment by sbaack** [comment]
OK ;-) I don't have this issue with any other syntax theme though, and in Pen Paper Coffee it appears no matter which UI theme I'm using with it. That's why I thought I should post it here

**Comment by nylki** [comment]
You are right! Good catch. I think it's because I add a margin to the editor at the top. Didn't expect this to influence popups like these, to be honest. *sigh* As the increased text-size is temporarily gone, there is no need to add a margin to the top.

**Comment by sbaack** [comment]
Thanks again for fixing it :-) I feel your frustration - the bigger font size on headers looked great, I really hope there will be some progress with Atom to better support it
