### ISSUE TITLE
Markdown preview theme

### ISSUE THREAD

**Issue by humanfactors** [nylki/pen-paper-coffee-syntax#26]
Would you be able to add to the readme the settings you use to style the markdown preview plus with pen paper coffee?

**Comment by nylki** [comment]
@humanfactors Pretty sure I didn't modify styles for markdown preview plus. The differnt background color might be due to a different `markdown-preview` version.

**Comment by nylki** [comment]
I'll close this. @humanfactors if you got some interesting stylesheets to add, feel free to add a comment :)
