### ISSUE TITLE
softWrapHangingIndent for lists?

### ISSUE THREAD

**Issue by stefanprobst** [nylki/pen-paper-coffee-syntax#27]
Hi, thanks for your package!

I'm new to all of this, so there might be a very obvious answer, but:

Where can I set softWrapHangingIndent just for ordered/unordered lists?

**Comment by nylki** [comment]
Hi @stefanprobst,
Actually, I am also not sure how and if a syntax theme can manipulate the `soft wrap hanging indent. A quick search into the topic didn't yield any useful results for me.

You are probably off, by asking this again the [atom forum](https://discuss.atom.io/), the people there are usually very helpful. :)

**Comment by stefanprobst** [comment]
Thanks for closing this, I guess you saw the reply in the forums that this is indeed currently not possible.

**Comment by nylki** [comment]
@stefanprobst yep, saw it there. It's a bummer, I imagine it can be useful to only have it for unordered lists. Have a good week!
