### ISSUE TITLE
Convert to Xressources

### ISSUE THREAD

**Issue by notaduck** [nylki/pen-paper-coffee-syntax#32]
Hello. I hope it is okay to come with a request like this.
I've been using this theme for atom for quite some time now and would like to know if you have converted it to a .Xressources color theme? or know if it is exists?

**Comment by nylki** [comment]
Hi @notaduck,
It certainly is ok to ask this :)

However, I neither have converted it myself nor know anybody who has. But if you happen
to find a project that did or try something yourself, I'd be happy to hear about it!
