### ISSUE TITLE
more prominent stying of TODO, FIXME etc

### ISSUE THREAD

**Issue by nylki** [nylki/pen-paper-coffee-syntax#9]
Testing a background for those might be an idea. Now they are only violet, which is ok, but could be more visible.

**Comment by leipert** [comment]
+1. Are todos only styled as comments? `<!-- TODO -->`

**Comment by nylki** [comment]
> Are comments like `<!-- TODO -->` styled as todo? 
Yep:
![bildschirmfoto von 2015-03-08 12 11 46](https://cloud.githubusercontent.com/assets/1710598/6545542/6879900a-c58c-11e4-95d5-c549ee03097f.png)
